name: Package

on:
  workflow_run:
    workflows:
      - Validation
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: InstechSandbox/.github/.github/workflows/reusable-docker-build.yml@ee7c589b6edeb479707d21c3d256092319e7af88
    with:
      image-name: eudi-srv-web-issuing-frontend-eudiw-py
      dockerfile: Dockerfile
      push: false
      tags: |
        ghcr.io/instechsandbox/eudi-srv-web-issuing-frontend-eudiw-py:${{ github.event.workflow_run.head_sha || github.sha }}
        ghcr.io/instechsandbox/eudi-srv-web-issuing-frontend-eudiw-py:main